### ISSUE TITLE
Process data in order to implement category based searching

### ISSUE THREAD

**Issue by Redmega** [Redmega/licensed-mental-health-counselors-browser#5]
Blocks #1.

Data needs to be processed more. Instead of passing the array of values directly through, ideally each counselor collection needs to be converted to an object. Similar fields should be combined by type (E.g. Mailing address fields / practice address fields.

Mailing Address: 6 fields
Number: 2 fields
Practice Address: 5 fields

If we can combine these together, we can display them better.

**Comment by dsych** [comment]
Hey @Redmega do you mind if I give it a go?

**Comment by Redmega** [comment]
Go for it! I thought I was going to work on it so I removed the Hacktoberfest label, but I'll add it back. :)

**Comment by Redmega** [comment]
If you need any help, let me know!

**Comment by dsych** [comment]
[cellRenderer](https://github.com/bvaughn/react-virtualized/blob/master/docs/Column.md) seems to be designed to work with arrays. If we were to convert incoming data from array to an object, I am not exactly sure how that is going to work.

**Comment by dsych** [comment]
Nvm, there is a `dataKey`

**Comment by Redmega** [comment]
Yep! I believe that was the intent behind that prop -- to make working with arrays of objects easier.

**Comment by Redmega** [comment]
@dsych How is this coming along? Had the chance to work on it? Need any help?
